config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    authenticated :user do
      root "products#index", as: :root
    end
    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end
  resources :products
  resource :carts
  resources :orders
  resource :cust_sessions

  get 'carts/checkout', to: 'carts#checkout', as: 'CheckOut'
  get 'carts/history', to: 'carts#history', as: 'CheckOut_history'
  get 'carts/current', to: 'carts#current', as: 'current_orders'
  post 'orders/delete_all_orders', to: 'orders#delete_all_orders', as: 'delete_all_orders'
  get 'orders/mark_complete/:id', to: 'orders#mark_complete', as: 'mark_complete_orders'
  get 'carts/increase_quantity/:product_id', to: 'carts#increase_quantity', as: 'increase_quantity_carts'
  post 'sessions/create', to: 'sessions#create', as: 'create_user_session'
  post 'sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'
  post 'sessions/new_user', to: 'sessions#new_user', as: 'new_user'
  # root to: 'products#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qroder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-light bg-primary justify-content-between">
      <a class="navbar-brand text-light m-3" href="/">Qroder</a>
      <form class="form-inline mx-3">
        <% if(current_user) then %>
          <% if (current_user.role == 'customer') %>
            <%= link_to "Home", products_path , class: "btn btn-primary" %>
            <%= link_to "Cart", carts_path , class: "btn btn-primary" %>
            <%= link_to "Current Orders", current_orders_path() , class: "btn btn-primary" %>
          <% else %>
              <%= link_to "Purchase History", CheckOut_history_path() , class: "btn btn-primary" %>
              <%= link_to "Orders", orders_path , class: "btn btn-primary" %>
              <%= link_to "Products", root_path , class: "btn btn-primary" %>
            <% end %>   
          <%= link_to "Logout", logout_path , class: "btn btn-danger" %>
        <% else %>
              <%= link_to "Login", new_user_session_path , class: "btn btn-primary" %>
              <%= link_to "Signup", new_user_registration_path , class: "btn btn-primary" %>
        <% end %>
      </form>
    </nav>
    <% if(notice) then %>
    <p class="notice alert alert-success"><%= notice %></p>
    <% end %>
    <% if(alert) then %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <br>
    <br>
    <%= yield %>
  </body>
</html>